CREATE TABLE "air_ancillary_rules" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"rule_code" varchar(50) NOT NULL,
	"ancillary_code" varchar(50) NOT NULL,
	"airline_code" varchar(2),
	"origin" varchar(3),
	"destination" varchar(3),
	"pos" json NOT NULL,
	"channel" varchar(20) NOT NULL,
	"agent_tier" json NOT NULL,
	"cohort_codes" json,
	"condition_behavior" varchar(30),
	"adjustment_type" varchar(20) NOT NULL,
	"adjustment_value" numeric(10, 2),
	"priority" integer DEFAULT 1 NOT NULL,
	"status" varchar(20) DEFAULT 'ACTIVE',
	"valid_from" date NOT NULL,
	"valid_to" date NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "air_ancillary_rules_rule_code_unique" UNIQUE("rule_code")
);
--> statement-breakpoint
CREATE TABLE "dynamic_discount_rules" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"rule_code" varchar(50) NOT NULL,
	"fare_source" varchar(20) NOT NULL,
	"origin" varchar(3) NOT NULL,
	"destination" varchar(3) NOT NULL,
	"cabin_class" varchar(20) NOT NULL,
	"trip_type" varchar(20) NOT NULL,
	"pos" json NOT NULL,
	"market_region" varchar(50),
	"agent_tier" json NOT NULL,
	"cohort_codes" json,
	"channel" varchar(20) NOT NULL,
	"booking_window_min" integer,
	"booking_window_max" integer,
	"travel_window_min" integer,
	"travel_window_max" integer,
	"season_code" varchar(50),
	"adjustment_type" varchar(20) NOT NULL,
	"adjustment_value" numeric(10, 2) NOT NULL,
	"stackable" varchar(5) DEFAULT 'false',
	"priority" integer DEFAULT 1 NOT NULL,
	"status" varchar(20) DEFAULT 'ACTIVE',
	"valid_from" date NOT NULL,
	"valid_to" date NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "dynamic_discount_rules_rule_code_unique" UNIQUE("rule_code")
);
--> statement-breakpoint
CREATE TABLE "negotiated_fares" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"airline_code" varchar(2) NOT NULL,
	"fare_code" varchar(50) NOT NULL,
	"origin" varchar(3) NOT NULL,
	"destination" varchar(3) NOT NULL,
	"trip_type" varchar(20) NOT NULL,
	"cabin_class" varchar(20) NOT NULL,
	"base_net_fare" numeric(10, 2) NOT NULL,
	"currency" varchar(3) NOT NULL,
	"booking_start_date" date NOT NULL,
	"booking_end_date" date NOT NULL,
	"travel_start_date" date NOT NULL,
	"travel_end_date" date NOT NULL,
	"pos" json NOT NULL,
	"seat_allotment" integer,
	"min_stay" integer,
	"max_stay" integer,
	"blackout_dates" json,
	"eligible_agent_tiers" json NOT NULL,
	"eligible_cohorts" json,
	"remarks" text,
	"status" varchar(20) DEFAULT 'ACTIVE',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
